### ISSUE TITLE
Different tags for different servers

### ISSUE THREAD

**Issue by Atharv23m** [opencodeiiita/OC-discord-bot#36] opened 2022-12-23 15:15 UTC
Currently the tag commands are common for all servers.

- The tag commands created in a Server A should not be accesible in Server B.
- Edit the command so the tags remain server specific.
- [HINT] Create different .json file in the data folder for different servers and access them accordingly using server ID.

Submission guidelines -
Ask for the token of the bot to run the bot, privately on discord either from hdelic#6900 or JotaroKujo#9740.
Do not misuse the token, malpractices like spam or sharing token will lead to serious consequences.

**Comment by frikinomad** [comment] 2022-12-23 15:15
claim

**Comment by Atharv23m** [comment] 2022-12-23 15:24
@frikinomad you already have one issue assigned.

**Comment by frikinomad** [comment] 2022-12-23 15:25
Already have a pr for it

**Comment by frikinomad** [comment] 2022-12-23 15:25
Waiting for someone to merge it

**Comment by pvtr03** [comment] 2022-12-23 15:28
Assigned to @frikinomad

**Comment by pvtr03** [comment] 2022-12-25 16:55
@frikinomad whats your progress on this issue?

**Comment by pvtr03** [comment] 2022-12-26 09:43
The issue is open for claims again!

**Comment by GammaMicrowave** [comment] 2022-12-26 09:44
claim

**Comment by pvtr03** [comment] 2022-12-26 09:45
Assigned to @GammaMicrowave

**Closed as completed** 2022-12-27 19:33 UTC
Labels: Points: 30, Skilled
